title: Patrick Ferro Ribeiro
description: Web page about Code, Sport, Blog... and more.
author: Patrick Ferro Ribeiro
logo: /static/img/avatar.png
github: https://github.com/riberman
about: Developer Cyclist Student
year: 2019
age: 24

baseurl: "/"
url: "https://riberman.github.io"
timezone: America/Sao_Paulo

allowsearch: true

disqus_shortname: https-riberman-github-io
google_analytics: UA-113720530-2
comments: true

share:
  twitter_username: riberman
  fb_appid: 2087090814720473


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]

permalink: /:categories/:title/
