title: Patrick Ferro Ribeiro
description: Code, Sport, Blog
author: Patrick Ferro Ribeiro
logo: /static/img/avatar.png
github: https://github.com/riberman
about: Developer Cyclist Student

baseurl: ""
url: ""
timezone: America/Sao_Paulo

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-113720530-2

# Social
# facebook: https://www.facebook.com/patrickferroribeiro
# twitter: #Add your Twitter
# google-plus: #Add your Google+
# github: @riberman

share:
  twitter_username: \riberman
  fb_appid: patrickferroribeiro


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
