title: Patrick Ferro Ribeiro
description: Code, Sport, Blog
author: Patrick Ferro Ribeiro
logo: /static/img/avatar.png
github: https://github.com/riberman
about: Developer Cyclist Student

baseurl: ""
url: ""
timezone: America/Sao_Paulo

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-113720530-2

share:
  twitter_username: \riberman
  fb_appid: 2087090814720473


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
